"""
Model Context Protocol (MCP) implementation with Supabase backend.

This module manages the agent's memory and state using a real Supabase database.

To use this, you need to:
1. Have a Supabase project.
2. Create a table named 'agent_memory' with the following schema:
   - id: bigint (primary key, auto-incrementing)
   - created_at: timestamp with time zone (default: now())
   - agent_id: text (the unique identifier for the agent)
   - key: text (the key for the memory entry, e.g., 'last_task')
   - value: text (the value to be stored)
   Ensure you have a unique constraint on (agent_id, key) to prevent duplicates.
   CREATE TABLE agent_memory (
     id bigint generated by default as identity primary key,
     created_at timestamptz default now(),
     agent_id text not null,
     key text not null,
     value text,
     unique(agent_id, key)
   );
3. Set the following environment variables:
   - SUPABASE_URL: Your Supabase project URL.
   - SUPABASE_KEY: Your Supabase anon key.
"""

import os
from supabase import create_client, Client

class MCP:
    def __init__(self, agent_id: str):
        self.agent_id = agent_id
        self.db_client: Client = self._init_supabase()
        print(f"--- [MCP] Initialized for agent: {self.agent_id} and connected to Supabase. ---")

    def _init_supabase(self) -> Client:
        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_KEY")
        if not url or not key:
            raise ValueError("Supabase URL and Key must be set as environment variables.")
        return create_client(url, key)

    def update_context(self, key: str, value: str):
        """
        Saves or updates a key-value pair in the agent's persistent memory (Supabase).
        """
        print(f"--- [MCP] Saving to Supabase for agent '{self.agent_id}': {{ '{key}': '{value}' }} ---")
        try:
            # Upsert functionality: insert if new, update if exists
            self.db_client.table('agent_memory').upsert({
                'agent_id': self.agent_id,
                'key': key,
                'value': value
            }).execute()
            print("--- [MCP] Save complete. ---")
        except Exception as e:
            print(f"--- [MCP] ERROR: Failed to save context to Supabase: {e} ---")

    def get_context(self, key: str) -> str | None:
        """
        Retrieves a value from the agent's persistent memory (Supabase).
        """
        print(f"--- [MCP] Retrieving from Supabase for agent '{self.agent_id}', key: '{key}' ---")
        try:
            response = self.db_client.table('agent_memory').select('value').eq('agent_id', self.agent_id).eq('key', key).execute()
            if response.data:
                value = response.data[0]['value']
                print(f"--- [MCP] Retrieved value: '{value}' ---")
                return value
            else:
                print("--- [MCP] No value found for this key. ---")
                return None
        except Exception as e:
            print(f"--- [MCP] ERROR: Failed to retrieve context from Supabase: {e} ---")
            return None
